on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: prakashsurya/actions/sync-with-upstream@master
        with:
          upstream-repository: https://github.com/prakashsurya/drgn.git
          upstream-branch: test
          downstream-branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
